channels:
  - pytorch
  - dglteam
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.3
  - pytorch=1.12
  - torchvision
  - torchaudio
  - numpy=1.22
  - scipy=1.8
  - scikit-learn=1.1
  - pandas=1.4
  - matplotlib=3.5
  - networkx
  - dgl-cuda11.3
  - pip>=22.0
  - tqdm
  - pip:
    - epiweeks
# For development
  - ipykernel
  - jupyter
  - black
  - pylint
  - flake8
  - mypy
