include_cols = [
    # "retail_and_recreation_percent_change_from_baseline",
    # "grocery_and_pharmacy_percent_change_from_baseline",
    # "parks_percent_change_from_baseline",
    # "transit_stations_percent_change_from_baseline",
    # "workplaces_percent_change_from_baseline",
    # "residential_percent_change_from_baseline",
    "covidnet",
    "positiveIncr",
    # "cdc_negativeIncr",
    "cdc_hospitalized",
    "death_jhu_incidence",
    #     "dex_a",
    #     "apple_mobility",
    #    "fb_survey_wcli",
    #    "fb_survey_wili",
    "cdc_flu_hosp",
]

include_cols_flu = [
    # "retail_and_recreation_percent_change_from_baseline",
    # "grocery_and_pharmacy_percent_change_from_baseline",
    # "parks_percent_change_from_baseline",
    # "transit_stations_percent_change_from_baseline",
    # "workplaces_percent_change_from_baseline",
    # "residential_percent_change_from_baseline",
    "covidnet",
    "positiveIncr",
    # "cdc_negativeIncr",
    "cdc_hospitalized",
    "death_jhu_incidence",
    #     "dex_a",
    #     "apple_mobility",
    #    "fb_survey_wcli",
    #    "fb_survey_wili",
    "cdc_flu_hosp",
]

include_cols_old = [
    # "retail_and_recreation_percent_change_from_baseline",
    # "grocery_and_pharmacy_percent_change_from_baseline",
    # "parks_percent_change_from_baseline",
    # "transit_stations_percent_change_from_baseline",
    # "workplaces_percent_change_from_baseline",
    # "residential_percent_change_from_baseline",
    "covidnet",
    "positiveIncrease",
    "negativeIncrease",
    "totalTestResultsIncrease",
    "onVentilatorCurrently",
    "inIcuCurrently",
    "recovered",
    "hospitalizedIncrease",
    "death_jhu_incidence",
    "dex_a",
    #     "apple_mobility",
    "Number of Facilities Reporting",
    "CLI Percent of Total Visits",
]

states = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "X",
]
